name: 'Up Bank to Google Sheets'
description: 'Synchronises Up Bank transaction data to Google Sheets'
author: 'Yann Frizenschaf'
inputs:
  syncFromDate:
    required: true
    description: 'Earliest date to sync transactions from'
    default: '2022-10-01T00:00:00.000Z'
  upApiKey1:
    required: true
    description: 'Read-only API key 1 for Up Bank'
    default: ''
  upApiKey2:
    required: false
    description: 'Read-only API key 2 for Up Bank'
    default: ''
  googleSpreadsheetId:
    required: true
    description: 'ID of Google Sheet to sync data to'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
